# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: true
env: R_REMOTES_NO_ERRORS_FROM_WARNINGS=true

os:
  - linux
  - osx

r:
  - oldrel
  - release

after_success:
  - Rscript -e 'covr::codecov(type = "all")'
